[package]
name = "surreal-restapi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# anyhow = "1.0.70"
rocket = "0.5.0-rc.1"
# surreal = "0.4.1"
# tracing = "0.1.37"
# tracing-subscriber = "0.3.16"
